name: jbeam-edit
version: 0.0.4.0
github: webdevred/jbeam-edit
license: BSD-3-Clause
author: webdevred
maintainer: example@example.com
copyright: 2025 webdevred
data-files: examples/jbfl/*.jbfl
language: GHC2021

extra-source-files:
  - README.md
  - JBFL_DOCS.md
  - examples/README.md
  - examples/jbeam/*.jbeam
  - examples/formatted_jbeam/*.jbeam

category: Command Line, Jbeam, Beamng
synopsis: A fast and reliable command-line tool for parsing, formatting, and editing
  JBeam files, supporting consistent node renaming, reference updating, and JBFL-based
  formatting.
description: >-
  jbeam-edit is a Haskell-based CLI utility for BeamNG JBeam files. It parses complete
  JBeam structures, preserves comments and whitespace, formats files consistently,
  and can automatically rename nodes and update references. Custom formatting rules
  are supported via JBFL (JBeam Formatting Language). See the README for usage instructions
  and examples: https://github.com/webdevred/jbeam-edit#readme
tested-with: [GHC == 9.4.7, GHC == 9.6.6]

dependencies:
  - base >= 4.17 && < 5
  - bytestring >= 0.12
  - text >= 2.1
  - containers >= 0.6
  - megaparsec >= 9.6
  - scientific >= 0.3
  - directory >= 1.3
  - filepath >= 1.4
  - mtl >= 2.3

default-extensions: [OverloadedStrings, ImportQualifiedPost]

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

flags:
  dump-ast:
    description: Enable building the dump-ast executable
    manual: true
    default: false
  transformation:
    description: Enable transformation (experimental)
    manual: true
    default: false
  lsp-server:
    description: Enable LSP server (experimental)
    manual: true
    default: false
  windows-example-paths:
    description: Use executable-relative example paths (for Windows release builds)
    default: false
    manual: true

_jbeam-extra-lib: &jbeam-extra-lib
  verbatim:
    mixins: >-
      base hiding (Prelude)
      , relude (Relude as Prelude)
      , relude

internal-libraries:
  jbeam-edit-transformation:
    when:
      condition: flag(transformation)
      then:
        dependencies: [yaml, relude>=1.2]
      else:
        buildable: false
    source-dirs: src-extra/transformation
    dependencies: [jbeam-edit]
    <<: *jbeam-extra-lib
  jbeam-language-server:
    when:
      condition: flag(lsp-server) && impl(ghc >= 9.6.6)
      then:
        dependencies: [lsp>=2.7, relude>=1.2]
      else:
        buildable: false
    source-dirs: src-extra/language-server
    dependencies: [jbeam-edit]
    <<: *jbeam-extra-lib

library:
  source-dirs: src
  generated-other-modules: Paths_jbeam_edit
  when:
    - condition: flag(transformation)
      cpp-options: -DENABLE_TRANSFORMATION
    - condition: os(windows) && flag(windows-example-paths)
      cpp-options: -DWINDOWS_EXAMPLE_PATHS

_jbeam-lsp-common: &jbeam-lsp-common
  main: Main.hs
  ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
  when:
    condition: flag(lsp-server) && impl(ghc >= 9.6.6)
    then:
      dependencies: [jbeam-language-server]
    else:
      buildable: false
  dependencies: [jbeam-edit]

executables:
  jbeam-edit:
    main: Main.hs
    source-dirs: exe/jbeam-edit
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit]
    when:
      - condition: flag(transformation)
        dependencies: [jbeam-edit-transformation]
        cpp-options: -DENABLE_TRANSFORMATION
      - condition: os(windows)
        cpp-options: -DENABLE_WINDOWS_NEWLINES
  jbeam-lsp-server:
    source-dirs: exe/jbeam-lsp-server
    <<: *jbeam-lsp-common
  jbeam-lsp-test-server:
    source-dirs: tools/lsp-test-server
    <<: *jbeam-lsp-common
  jbeam-edit-dump-ast:
    when:
      condition: (flag(dump-ast) && flag(transformation))
      then:
        dependencies: [pretty-simple>=4.1, jbeam-edit-transformation]
      else:
        buildable: false
    main: Main.hs
    source-dirs: tools/dump_ast
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit]

_jbeam-test-common: &jbeam-test-common
  main: Spec.hs
  ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
  build-tools: [hspec-discover]
  dependencies: [jbeam-edit, hspec>=2.11]

tests:
  jbeam-edit-test:
    <<: *jbeam-test-common
    source-dirs: test
    when:
      - condition: true
        dependencies: [hspec-megaparsec>=2.2]
      - condition: flag(transformation)
        dependencies: [jbeam-edit-transformation]
        cpp-options: -DENABLE_TRANSFORMATION_TESTS
  jbeam-language-server-test:
    <<: *jbeam-test-common
    source-dirs: test-extra/language-server
    when:
      - condition: flag(lsp-server) && impl(ghc >= 9.6.6)
        then:
          dependencies: [jbeam-language-server, lsp-test, lsp>=2.7]
        else:
          buildable: false
