name: jbeam-edit
version: 0.0.1.0
github: webdevred/jbeam-edit
license: BSD-3-Clause
author: webdevred
maintainer: example@example.com
copyright: 2025 webdevred
data-files: examples/jbfl/*.jbfl

extra-source-files:
  - README.md
  - JBFL_DOCS.md
  - examples/README.md
  - examples/jbeam/*.jbeam

description: Please see the README on GitHub at <https://github.com/webdevred/jbeam-edit#readme>
tested-with: [GHC == 9.4.7, GHC == 9.6.6]

dependencies:
  - base >= 4.17 && < 5
  - bytestring
  - vector
  - text >= 2.0
  - containers
  - megaparsec
  - scientific
  - foldable1-classes-compat
  - directory
  - filepath

default-extensions: [OverloadedStrings, ImportQualifiedPost]

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  generated-other-modules: Paths_jbeam_edit
  when:
    - condition: flag(transformation)
      source-dirs: [src-extra/transformation]
      exposed-modules: [Transformation]
      other-modules: [Types]
    - condition: os(windows) && flag(windows-example-paths)
      cpp-options: -DWINDOWS_EXAMPLE_PATHS

flags:
  dump-ast:
    description: Enable building the dump-ast executable
    manual: true
    default: false
  transformation:
    description: Enable transformation (experimental)
    manual: true
    default: false
  windows-example-paths:
    description: Use executable-relative example paths (for Windows release builds)
    default: false
    manual: true

executables:
  jbeam-edit:
    main: Main.hs
    source-dirs: app
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit]
    when:
      condition: flag(transformation)
      cpp-options: -DENABLE_TRANSFORMATION
  jbeam-edit-dump-ast:
    when:
      condition: flag(dump-ast)
      then:
        buildable: true
      else:
        buildable: false
    main: Main.hs
    source-dirs: tools/dump_ast
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [pretty-simple, jbeam-edit]

tests:
  jbeam-edit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit, hspec, hspec-megaparsec]
    build-tools: [hspec-discover]
