name: jbeam-edit
version: 0.0.2.0
github: webdevred/jbeam-edit
license: BSD-3-Clause
author: webdevred
maintainer: example@example.com
copyright: 2025 webdevred
data-files: examples/jbfl/*.jbfl
category: Command Line, Jbeam, Beamng
synopsis: A fast, robust command-line parser, formatter, and editor for JBeam files,
  the JSON-like format used by BeamNG to define vehicles and physics structures.

extra-source-files:
  - README.md
  - JBFL_DOCS.md
  - examples/README.md
  - examples/jbeam/*.jbeam
  - examples/formatted_jbeam/*.jbeam

description: Please see the README on GitHub at <https://github.com/webdevred/jbeam-edit#readme>
tested-with: [GHC == 9.4.7, GHC == 9.6.6]

dependencies:
  - name: base
    version: '>= 4.17 && < 5'
    mixin: [hiding (Prelude)]
  - name: relude
    mixin: [(Relude as Prelude), '']
  - bytestring
  - vector
  - text >= 2.0
  - containers
  - megaparsec
  - scientific
  - directory
  - filepath

default-extensions: [OverloadedStrings, ImportQualifiedPost]

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

flags:
  dump-ast:
    description: Enable building the dump-ast executable
    manual: true
    default: false
  transformation:
    description: Enable transformation (experimental)
    manual: true
    default: false
  windows-example-paths:
    description: Use executable-relative example paths (for Windows release builds)
    default: false
    manual: true

internal-libraries:
  jbeam-edit-transformation:
    source-dirs: src-extra/transformation
    dependencies: [yaml, jbeam-edit]

library:
  source-dirs: src
  generated-other-modules: Paths_jbeam_edit
  when:
    - condition: flag(transformation)
      cpp-options: -DENABLE_TRANSFORMATION
    - condition: os(windows) && flag(windows-example-paths)
      cpp-options: -DWINDOWS_EXAMPLE_PATHS

executables:
  jbeam-edit:
    main: Main.hs
    source-dirs: app
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit]
    when:
      condition: flag(transformation)
      dependencies: [jbeam-edit-transformation]
      cpp-options: -DENABLE_TRANSFORMATION
  jbeam-edit-dump-ast:
    when:
      condition: flag(dump-ast) && flag(transformation)
      then:
        buildable: true
      else:
        buildable: false
    main: Main.hs
    source-dirs: tools/dump_ast
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [pretty-simple, jbeam-edit, jbeam-edit-transformation]

tests:
  jbeam-edit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit, hspec, hspec-megaparsec]
    build-tools: [hspec-discover]
    when:
      condition: flag(transformation)
      dependencies: [jbeam-edit-transformation]
      cpp-options: -DENABLE_TRANSFORMATION_TESTS
