name: jbeam-edit
version: 0.1.0.0
github: webdevred/jbeam-edit
license: BSD-3-Clause
author: webdevred
maintainer: example@example.com
copyright: 2025 webdevred
data-files: examples/jbfl/*.jbfl

extra-source-files:
  - README.md
  - JBFL_DOCS.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/webdevred/jbeam-edit#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - vector
  - text >= 2.0
  - containers
  - megaparsec
  - scientific
  - foldable1-classes-compat
  - directory
  - filepath

default-extensions: [OverloadedStrings, ImportQualifiedPost]

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  generated-other-modules: Paths_jbeam_edit

flags:
  dump-ast:
    description: Enable building the dump-ast executable
    manual: true
    default: false

executables:
  jbeam-edit:
    main: Main.hs
    source-dirs: app
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit]
  jbeam-edit-dump-ast:
    when:
      condition: flag(dump-ast)
      then:
        buildable: true
      else:
        buildable: false
    main: Main.hs
    source-dirs: tools/dump_ast
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [pretty-simple, jbeam-edit]

tests:
  jbeam-edit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit, hspec, hspec-megaparsec]
    build-tools: [hspec-discover]
