name: jbeam-edit
version: 0.0.5.0
github: webdevred/jbeam-edit
license: BSD-3-Clause
author: webdevred
maintainer: example@example.com
copyright: 2025 webdevred
data-files: examples/jbfl/*.jbfl
language: GHC2021

extra-source-files:
  - README.md
  - JBFL_DOCS.md
  - examples/README.md
  - examples/jbeam/*.jbeam
  - examples/formatted_jbeam/*.jbeam

category: Command Line, Jbeam, Beamng
synopsis: A fast and reliable command-line tool for parsing, formatting, and editing
  JBeam files, supporting consistent node renaming, reference updating, and JBFL-based
  formatting.
description: >-
  jbeam-edit is a Haskell-based CLI utility for BeamNG JBeam files. It parses complete
  JBeam structures, preserves comments and whitespace, formats files consistently,
  and can automatically rename nodes and update references. Custom formatting rules
  are supported via JBFL (JBeam Formatting Language). See the README for usage instructions
  and examples: https://github.com/webdevred/jbeam-edit#readme
tested-with: [GHC == 9.6.6]

dependencies:
  - base >= 4.18 && < 5
  - bytestring
  - vector
  - text >= 2.1.2
  - containers
  - scientific
  - directory
  - filepath >= 1.5.1.0
  - mtl

default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost
  - DerivingStrategies

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

when:
  condition: os(windows)
  ghc-options:
    -optc-Os
    -optl-static

flags:
  dump-ast:
    description: Enable building the dump-ast executable (dev-only)
    manual: true
    default: false
  transformation:
    description: Enable transformation (experimental)
    manual: true
    default: false
  lsp-server:
    description: Enable LSP server (experimental)
    manual: true
    default: false
  windows-example-paths:
    description: Use executable-relative example paths (for Windows release builds)
    default: false
    manual: true

internal-libraries:
  jbeam-edit-transformation:
    when:
      condition: flag(transformation)
      then:
        dependencies: [yaml, extra, transformers, ordered-containers]
      else:
        buildable: false
    source-dirs: src-extra/transformation
    dependencies: [jbeam-edit]
  jbeam-language-server:
    default-extensions: [DataKinds, PolyKinds]
    when:
      condition: flag(lsp-server)
      then:
        dependencies: [lsp >= 2.7, co-log-core]
      else:
        buildable: false
    source-dirs: src-extra/language-server
    dependencies: [jbeam-edit]

library:
  ghc-options: [-Wunused-packages]
  source-dirs: src
  generated-other-modules: Paths_jbeam_edit
  dependencies: [megaparsec, file-io]
  when:
    - condition: flag(transformation)
      cpp-options: -DENABLE_TRANSFORMATION
    - condition: os(windows) && flag(windows-example-paths)
      cpp-options: -DWINDOWS_EXAMPLE_PATHS

_jbeam-lsp-common: &jbeam-lsp-common
  main: Main.hs
  dependencies: [jbeam-edit]
_jbeam-options: &jbeam-options
  main: Main.hs
  ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]

executables:
  jbeam-edit:
    <<: *jbeam-options
    source-dirs: exe/jbeam-edit
    default-extensions: [CPP]
    dependencies: [jbeam-edit, file-io]
    when:
      - condition: flag(transformation)
        dependencies: [jbeam-edit-transformation]
        cpp-options: -DENABLE_TRANSFORMATION
      - condition: os(windows)
        cpp-options: -DENABLE_WINDOWS_NEWLINES
  jbeam-lsp-server:
    source-dirs: exe/jbeam-lsp-server
    when:
      condition: flag(lsp-server)
      then:
        dependencies: [jbeam-language-server]
      else:
        buildable: false
    <<:
      - *jbeam-options
      - *jbeam-lsp-common
  jbeam-edit-dump-ast:
    <<: *jbeam-options
    when:
      condition: (flag(dump-ast) && flag(transformation))
      then:
        dependencies: [pretty-simple>=3.3, jbeam-edit-transformation]
      else:
        buildable: false
    source-dirs: tools/dump_ast
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [jbeam-edit]

benchmarks:
  jbeam-edit-bench:
    <<: *jbeam-options
    source-dirs: tools/bench
    dependencies: [base, jbeam-edit]
    when:
      - condition: flag(transformation)
        then:
          dependencies: [criterion, jbeam-edit-transformation]
        else:
          buildable: false

_jbeam-test-common: &jbeam-test-common
  <<: *jbeam-options
  main: Spec.hs
  build-tools: [hspec-discover]
  dependencies: [jbeam-edit, hspec]

tests:
  jbeam-edit-test:
    <<: *jbeam-test-common
    source-dirs: test
    when:
      - condition: true
        dependencies: [megaparsec, hspec-megaparsec]
  jbeam-language-server-test:
    <<: *jbeam-test-common
    source-dirs: test-extra/language-server
    when:
      - condition: flag(lsp-server)
        then:
          build-tools: jbeam-edit:jbeam-lsp-server
          dependencies: [jbeam-language-server, lsp-test, lsp >= 2.7]
        else:
          buildable: false
  jbeam-edit-transformation-test:
    <<: *jbeam-test-common
    main: Spec.hs
    build-tools: []
    source-dirs: test-extra/transformation
    when:
      - condition: true
        ghc-options: -main-is Spec
      - condition: flag(transformation)
        then:
          dependencies: [jbeam-edit-transformation]
        else:
          buildable: false
