snapshot: lts-24.21
packages: [.]

flags:
  jbeam-edit:
    lsp-server: false
    transformation: false
    dump-ast: false
    windows-example-paths: false

ghc-options:
  jbeam-edit: "-Werror -Wwarn=unused-imports"
