name: Build and test on Windows

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-with-stack-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Stack state and GHC install
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~\AppData\Local\Programs\stack
            ~\AppData\Roaming\stack
            .stack-work
          key: >-
            ${{ runner.os }}-stack-${{ hashFiles(
              '**/stack.yaml.lock',
              '**/package.yaml'
            )}}
          restore-keys: |
            ${{ runner.os }}-stack-
      - name: Set up GHC with Stack
        run: stack setup
      - name: Build project
        run: >
          stack build --fast --hpack-force --lock-file=error-on-write
          --ghc-options="-Werror"
      - name: Run tests
        run: stack test --fast
  build-with-cabal-windows:
    name: Build and test with Cabal (GHC latest, future-proof)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up GHC latest and Cabal
        id: setup-ghc
        uses: haskell-actions/setup@v2.8.0
        with:
          ghc-version: latest
          cabal-version: latest
          cabal-update: true
      - name: Cache GHC, Cabal store, and build artifacts
        uses: actions/cache@v4.2.3
        with:
          path: |
            dist-newstyle
            ${{ steps.setup-ghc.outputs.cabal-store }}
          key: >-
            ${{ runner.os }}-cabal-${{
               steps.setup-ghc.outputs.ghc-version
            }}-${{
              hashFiles('**/package.yaml')
            }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ steps.setup-ghc.outputs.ghc-version }}-
      - name: Configure project
        shell: pwsh
        run: |
          cabal configure --enable-tests --flags=dump-ast --allow-newer=base --ghc-options="-Werror"
      - name: Build project (GHC latest)
        run: cabal build
      - name: Run tests (GHC latest)
        run: cabal test --test-show-details=direct
