name: Build and test on Ubuntu

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-with-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Stack and binaries
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.stack
            ~/.ghc
            .stack-work
          key: >-
            ${{ runner.os }}-stack-${{
              hashFiles('**/stack.yaml.lock')
            }}-${{
              hashFiles('**/package.yaml')
            }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-
            ${{ runner.os }}-stack-
      - name: Set up GHC with Stack
        run: stack setup
      - name: Build project
        run: >
          stack build --fast --hpack-force --lock-file=error-on-write
          --ghc-options="-Werror"
      - name: Check that .cabal file has not changed except hpack comment
        run: |
          CABAL_FILE=jbeam-edit.cabal
          TMP_DIR=$(mktemp -d)
          git show HEAD:$CABAL_FILE > $TMP_DIR/committed.cabal
          cp $CABAL_FILE $TMP_DIR/current.cabal
          sed '/^-- This file has been generated from package.yaml by hpack/d' \
            $TMP_DIR/committed.cabal > $TMP_DIR/committed_filtered.cabal
          sed '/^-- This file has been generated from package.yaml by hpack/d' \
            $TMP_DIR/current.cabal > $TMP_DIR/current_filtered.cabal
          if ! diff -q $TMP_DIR/committed_filtered.cabal \
                $TMP_DIR/current_filtered.cabal > /dev/null; then
            echo "Error: .cabal file changed beyond the expected hpack comment line."
            echo "Only package.yaml should be edited. Regenerate the .cabal file with hpack."
            echo "Manual changes to the .cabal file are not allowed and must be reverted."
            exit 1
          else
            echo ".cabal file is unchanged except for the hpack comment line."
          fi
      - name: Run tests
        run: stack test --fast
  build-with-cabal:
    # Cabal matrix build:
    # This job builds and tests the project using multiple GHC versions.
    # - Ensures compatibility with stable compiler versions (e.g. 9.4.7, 9.6.6).
    # - Tests with 'latest' GHC to catch breaking changes early.
    # - Uses '--allow-newer=base' with 'latest' to relax bounds for future compatibility.
    # - Enables the 'dump-ast' flag to ensure internal tooling builds correctly.
    name: Build and test with Cabal (GHC ${{ matrix.ghc }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [9.4.7, 9.6.6, latest]
    env:
      MATRIX_GHC: ${{ matrix.ghc }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up GHC ${{ matrix.ghc }} and Cabal
        id: setup-ghc
        uses: haskell-actions/setup@v2.8.0
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
          cabal-update: true
      - name: Cache GHC, Cabal store, and build artifacts
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.ghc
            ~/.cabal/store
            dist-newstyle
          key: >-
            ${{ runner.os }}-cabal-${{
              steps.setup-ghc.outputs.ghc-version
            }}-${{
              hashFiles('**/package.yaml')
            }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ steps.setup-ghc.outputs.ghc-version }}-
      - name: Configure project
        run: |
          FLAGS=""
          if [ "${MATRIX_GHC}" = "latest" ]; then
            FLAGS="--allow-newer=base"
          fi
          cabal configure --enable-tests --flags=dump-ast $FLAGS --ghc-options="-Werror"
      - name: Build project (GHC ${{ steps.setup-ghc.outputs.ghc-version }})
        run: cabal build
      - name: Run tests (GHC ${{ steps.setup-ghc.outputs.ghc-version }})
        run: cabal test --test-show-details=direct
