name: Build and test on Windows

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: 0 5 * * 0  # every sunday 05:00 UTC

jobs:
  build-with-stack-windows:
    name: Build and test with Stack
    if: github.event_name != 'schedule'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Stack state and GHC install
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~\AppData\Local\Programs\stack
            ~\AppData\Roaming\stack
            .stack-work
          key: >-
            ${{ runner.os }}-stack-${{
              hashFiles('**/stack.yaml.lock')
            }}-${{
              hashFiles('**/package.yaml')
            }}
          restore-keys: |-
            ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-
            ${{ runner.os }}-stack-
      - name: Set up GHC with Stack
        run: stack setup
      - name: Build project
        run: >-
          stack build --fast --hpack-force --lock-file=error-on-write
          --ghc-options="-Werror"
      - name: Run tests
        run: stack test --fast
