name: Build and test on Ubuntu

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-with-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Stack and binaries
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.ghcup
            ~/.stack
            ~/.ghc
            .stack-work
          key: >-
            ${{ runner.os }}-stack-${{ hashFiles(
              '**/stack.yaml.lock',
              '**/package.yaml'
            ) }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - name: Set up GHC with Stack
        run: stack setup
      - name: Build project
        run: >
          stack build --fast --hpack-force --lock-file=error-on-write
          --ghc-options="-Werror"
      - name: Check that .cabal file has not changed except hpack comment
        run: |
          CABAL_FILE=jbeam-edit.cabal
          TMP_DIR=$(mktemp -d)
          git show HEAD:$CABAL_FILE > $TMP_DIR/committed.cabal
          cp $CABAL_FILE $TMP_DIR/current.cabal
          sed '/^-- This file has been generated from package.yaml by hpack/d' \
            $TMP_DIR/committed.cabal > $TMP_DIR/committed_filtered.cabal
          sed '/^-- This file has been generated from package.yaml by hpack/d' \
            $TMP_DIR/current.cabal > $TMP_DIR/current_filtered.cabal
          if ! diff -q $TMP_DIR/committed_filtered.cabal \
                $TMP_DIR/current_filtered.cabal > /dev/null; then
            echo "Error: .cabal file changed beyond the expected hpack comment line."
            echo "Only package.yaml should be edited. Regenerate the .cabal file with hpack."
            echo "Manual changes to the .cabal file are not allowed and must be reverted."
            exit 1
          else
            echo ".cabal file is unchanged except for the hpack comment line."
          fi
      - name: Run tests
        run: stack test --fast
  build-with-cabal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [9.4.7, 9.6.6]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache GHC, Cabal store, and build artifacts
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.ghcup
            ~/.ghc
            ~/.cabal/store
            dist-newstyle
          key: >-
            ${{ runner.os }}-cabal-${{ matrix.ghc }}-${{
              hashFiles('**/package.yaml')
            }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ matrix.ghc }}-
            ${{ runner.os }}-cabal-
      - name: Set up GHC ${{ matrix.ghc }} and Cabal
        uses: haskell-actions/setup@v2.8.0
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
          cabal-update: true
      - run: cabal configure --enable-tests
      - name: Build project (GHC ${{ matrix.ghc }})
        run: cabal build --ghc-options="-Werror"
      - name: Run tests (GHC ${{ matrix.ghc }})
        run: cabal test --test-show-details=direct
  build-on-latest:
    name: Build-and-and-test-with-ghc-latest
    needs: build-with-cabal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache GHC, Cabal store, and build artifacts
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.ghcup
            ~/.ghc
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-latest-store-${{ hashFiles('**/package.yaml')}}
          restore-keys: |
            ${{ runner.os }}-cabal-latest-store-
            ${{ runner.os }}-cabal-
      - name: Set up GHC latest and Cabal
        uses: haskell-actions/setup@v2.8.0
        with:
          ghc-version: latest
          cabal-version: latest
          cabal-update: true
      - name: Configure with dump-ast flag
        run: cabal configure --enable-test --allow-newer=base --flags=dump-ast
      - name: Build
        run: cabal build
      - name: Run tests
        run: cabal test --test-show-details=direct
