name: Haskell Stack CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: 'latest'

    - name: Run hlint
      uses: haskell-actions/hlint-run@v2.4.10
      with:
        fail-on: warning

    - name: Run fourmolu
      uses: haskell-actions/run-fourmolu@v11
      with:
        version: "latest"

    - name: Cache Stack and binaries
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}

    - name: Set up GHC with Stack
      run: stack setup

    - name: Build project
      run: stack build --fast --ghc-options="-Werror"

    - name: Run tests
      run: stack test --fast
