name: Haskell Stack CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install hlint
      run: sudo apt install -y hlint

    - name: Run hlint
      run: hlint .

    - name: Run fourmolu
      uses: haskell-actions/run-fourmolu@v11
      with:
        version: "latest"

    - name: Cache Stack and binaries
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}

    - name: Set up GHC with Stack
      run: stack setup

    - name: Build project
      run: stack build --fast

    - name: Run tests
      run: stack test --fast
