name: Haskell Stack CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: 'latest'

    - name: Run hlint
      uses: haskell-actions/hlint-run@v2.4.10
      with:
        fail-on: warning

    - name: Run fourmolu
      uses: haskell-actions/run-fourmolu@v11
      with:
        version: "latest"

  build-with-stack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Stack and binaries
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}

    - name: Set up GHC with Stack
      run: stack setup

    - name: Build project
      run: stack build --fast --ghc-options="-Werror"

    - name: Check that .cabal file has not changed except hpack comment
      run: |
        CABAL_FILE=jbeam-edit.cabal
        TMP_DIR=$(mktemp -d)
        git show HEAD:$CABAL_FILE > $TMP_DIR/committed.cabal
        cp $CABAL_FILE $TMP_DIR/current.cabal
        tail -n +2 $TMP_DIR/committed.cabal > $TMP_DIR/committed_trimmed.cabal
        tail -n +2 $TMP_DIR/current.cabal > $TMP_DIR/current_trimmed.cabal

        if ! diff -q $TMP_DIR/committed_trimmed.cabal $TMP_DIR/current_trimmed.cabal > /dev/null; then
        echo "Error: .cabal file has changed beyond the expected hpack comment line."
        echo "Please commit the updated .cabal file if this is intentional."
        exit 1
        else
        echo ".cabal file is unchanged except for the first comment line."
        fi

    - name: Run tests
      run: stack test --fast

  build-with-cabal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GHC and Cabal (GHC 9.4.7)
      uses: haskell-actions/setup@v2
      with:
        ghc-version: 9.4.7
        cabal-version: latest
        cabal-update: true

    - name: Cache Cabal build and dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/jbeam-edit.cabal') }}

    - name: Configure build
      run: cabal configure --enable-tests --disable-documentation

    - name: Build project
      run: cabal build

    - name: Run tests
      run: cabal test
